-- Create Database
CREATE DATABASE IF NOT EXISTS ecommerce_reviews;
USE ecommerce_reviews;

-- Tables auto-generated by Hibernate. Blueprint reference below.

-- CREATE TABLE reviews (
--   id BIGINT AUTO_INCREMENT PRIMARY KEY,
--   product_id BIGINT NOT NULL,
--   user_id BIGINT NOT NULL,
--   user_name VARCHAR(100) NOT NULL,
--   rating TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
--   title VARCHAR(120) NOT NULL,
--   body TEXT NOT NULL,
--   status VARCHAR(20) NOT NULL DEFAULT 'PENDING',     -- PENDING, APPROVED, REJECTED
--   is_verified_purchase BOOLEAN NOT NULL DEFAULT FALSE,
--   helpful_count INT NOT NULL DEFAULT 0,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   UNIQUE KEY uq_product_user (product_id, user_id),
--   INDEX idx_product_status (product_id, status)
-- );

-- Sample seed data (uncomment to use after service start)
-- INSERT INTO reviews (product_id, user_id, user_name, rating, title, body, status, is_verified_purchase)
-- VALUES
--   (1, 10, 'Alice M.', 5, 'Absolutely love it!', 'This product exceeded all my expectations. The build quality is fantastic and it works perfectly.', 'APPROVED', TRUE),
--   (1, 11, 'Bob K.', 4, 'Great value for money', 'Solid product. A few minor issues but nothing deal-breaking. Would buy again.', 'APPROVED', TRUE),
--   (1, 12, 'Carol S.', 2, 'Disappointed', 'The product stopped working after 2 weeks. Not happy with the quality control.', 'PENDING', FALSE),
--   (2, 10, 'Alice M.', 5, 'Best purchase this year', 'Highly recommend this to everyone looking for a reliable product at this price range.', 'APPROVED', TRUE);
