-- Create Database
CREATE DATABASE IF NOT EXISTS ecommerce_analytics;
USE ecommerce_analytics;

-- Tables auto-generated by Hibernate (ddl-auto=update)

-- CREATE TABLE analytics_events (
--   id BIGINT AUTO_INCREMENT PRIMARY KEY,
--   event_type VARCHAR(30) NOT NULL,   -- PAGE_VIEW, PRODUCT_VIEW, ADD_TO_CART, PURCHASE, SEARCH
--   user_id BIGINT NULL,
--   product_id BIGINT NULL,
--   metadata JSON NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   INDEX idx_event_type (event_type),
--   INDEX idx_product_id (product_id),
--   INDEX idx_created_at (created_at)
-- );

-- CREATE TABLE sales_snapshots (
--   id BIGINT AUTO_INCREMENT PRIMARY KEY,
--   date DATE NOT NULL UNIQUE,
--   total_orders BIGINT NOT NULL DEFAULT 0,
--   total_revenue DECIMAL(12,2) NOT NULL DEFAULT 0,
--   total_items_sold BIGINT NOT NULL DEFAULT 0,
--   new_users BIGINT NOT NULL DEFAULT 0,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- Note: Demo daily snapshots (last 30 days) are auto-seeded by ReportService.seedDemoSnapshots()
-- on application startup via @PostConstruct. No manual seed needed.
