-- Create Database
CREATE DATABASE IF NOT EXISTS ecommerce_auth;
USE ecommerce_auth;

-- Insert Roles (Since we use ddl-auto=update, tables are generated, but we can seed roles manually)
CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) NOT NULL UNIQUE
);

INSERT IGNORE INTO roles (name) VALUES 
('ROLE_CUSTOMER'), 
('ROLE_SELLER'), 
('ROLE_ADMIN');

-- Password for admin is 'admin123'
-- Hash generated by BCrypt: $2a$10$XbL/FkP9a1QeW1fX/Q2N1uA3B4XbL..
-- We can add a script to insert default admin:
-- INSERT IGNORE INTO users (name, email, password_hash, phone, role_id, is_verified, created_at) VALUES 
-- ('Admin', 'admin@ecommerce.com', '$2a$10$wN1Q/y10wY/2U3HkZJ9O7eq1K1gTjYpW1R2M3Iq2T3wL3mXv0Z3vW', '1234567890', 3, true, NOW());

-- (For simplicity, roles are enough. Users can be created via register API).
