-- Create Database
CREATE DATABASE IF NOT EXISTS ecommerce_inventory;
USE ecommerce_inventory;

-- Tables auto-generated by Hibernate (ddl-auto=update). This is a blueprint reference.

-- CREATE TABLE inventories (
--   id BIGINT AUTO_INCREMENT PRIMARY KEY,
--   product_id BIGINT NOT NULL,
--   variant_id BIGINT NULL,
--   warehouse_location VARCHAR(100) NOT NULL DEFAULT 'MAIN',
--   quantity_available INT NOT NULL DEFAULT 0,
--   quantity_reserved INT NOT NULL DEFAULT 0,
--   low_stock_threshold INT NOT NULL DEFAULT 10,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   UNIQUE KEY uxq_product_variant (product_id, variant_id),
--   INDEX idx_product_id (product_id)
-- );

-- CREATE TABLE stock_movements (
--   id BIGINT AUTO_INCREMENT PRIMARY KEY,
--   product_id BIGINT NOT NULL,
--   movement_type VARCHAR(30) NOT NULL,  -- STOCK_IN, STOCK_OUT, RESERVED, RELEASED, ADJUSTMENT
--   quantity INT NOT NULL,
--   reference_id BIGINT NULL,
--   reference_type VARCHAR(30) NULL,     -- ORDER, RETURN, MANUAL
--   notes TEXT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   INDEX idx_product_id (product_id)
-- );

-- Seed Some Initial Inventory Records (uncomment to use)
-- INSERT INTO inventories (product_id, warehouse_location, quantity_available, quantity_reserved, low_stock_threshold)
-- VALUES
--   (1, 'MAIN', 150, 0, 20),
--   (2, 'MAIN', 8,  2, 15),
--   (3, 'EAST', 0,  0, 5),
--   (4, 'MAIN', 45, 5, 10),
--   (5, 'WEST', 200, 10, 25);
